version: '3'

services:
  db:
    build:
      context: ./container1
    container_name: database
    volumes:
      - ./container1:/app
    networks:
      - app_network

  app:
    build:
      context: ./container2
    container_name: app_entry_point
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
